<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>breast_cancer_ml</title>

<script src="site_libs/header-attrs-2.30/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.5.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Jiye Choi</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Stat/ML
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="breast_cancer_ml.html">Breast Cancer Prediction Analysis using ML Methods</a>
    </li>
    <li>
      <a href="stat1.html">Bank Customer Behavior Analysis</a>
    </li>
    <li>
      <a href="stat2.html">Regional Birth Rate Disparities in South Korea</a>
    </li>
    <li>
      <a href="stat3.html">Forecasting Jeju Island Tourism Revenue</a>
    </li>
    <li>
      <a href="stat4.html">Fackbook National Geographic Engagement Analysis</a>
    </li>
    <li>
      <a href="stat5.html">Analyzing Monthly Living Expenses</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="contact.html">
    <span class="fas fa-envelope"></span>
     
  </a>
</li>
<li>
  <a href="files/Resume_Jiye_Choi.pdf">
    <span class="ai ai-cv ai-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://www.linkedin.com/in/jiyechoi-data/">
    <span class="fab fa-linkedin-in"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">




</div>


<style>
  body {
    font-family: Georgia, "Times New Roman", Times, serif;
  }

  h1, h2 {
    color: #333;
  }
</style>
<p><link rel="stylesheet" href="styles.css" type="text/css">
<link rel="stylesheet" href="site_libs/academicons-1.9.1/css/academicons.min.css"/></p>
<p><br><br><br></p>
<div id="breast-cancer-prediction-analysis-using-ml-methods"
class="section level2">
<h2><strong>Breast Cancer Prediction Analysis using ML
Methods</strong></h2>
<p><img src="https://img.shields.io/badge/Using-R-blue" /> <img
src="https://img.shields.io/badge/Method-Logistic%20%7C%20LASSO%20%7C%20Tree%20%7C%20RF%20%7C%20XGBoost-orange" />
<img
src="https://img.shields.io/badge/Data-UCI_Breast_Cancer_Wisconsin-green" />
<img
src="https://img.shields.io/badge/Evaluation-ROC%2FAUC%20%7C%20Sensitivity%20%7C%20Confusion_Matrix-purple" /></p>
<p><br></p>
<p><br><br><br></p>
<div id="introduction" class="section level3">
<h3>1. Introduction</h3>
<p><br> Breast cancer is one of the most prevalent cancers worldwide,
making early and accurate diagnosis critical for improving patient
outcomes. This project applies a comparative machine learning approach
to the UCI Breast Cancer Wisconsin dataset, evaluating multiple
classification models to distinguish malignant from benign tumors.</p>
<p><br><br><br></p>
</div>
<div id="goal" class="section level3">
<h3>2. Goal</h3>
<p><br> This project develops and compares five classification models —
Logistic Regression, LASSO, Decision Tree, Random Forest, and XGBoost —
for breast cancer prediction. Model performance is evaluated with a
focus on sensitivity and ROC/AUC, given the severe clinical consequences
of misclassifying malignant tumors as benign.</p>
<p><br><br><br></p>
</div>
<div id="exploratory-data-analysis" class="section level3">
<h3>3. Exploratory Data Analysis</h3>
<p><br><br></p>
<div id="data-preprocessing" class="section level4">
<h4>3-1. Data Preprocessing</h4>
<p><br><br> The raw dataset contains <strong>699 observations and 11
variables</strong>, including one patient ID variable, 9 cytological
predictors scored on a 1–10 scale, and one binary target variable
(<code>Class</code>). <br><br><br> Three preprocessing steps were
applied prior to analysis:</p>
<p><br> <strong>1. Missing value removal</strong><br />
16 observations with missing values in <code>Bare.nuclei</code> were
removed using <code>na.omit()</code>, resulting in a final dataset of
<strong>683 observations</strong>. <br><br></p>
<p><strong>2. ID column removal</strong><br />
The <code>Id</code> variable was excluded as it serves as a patient
identifier and carries no predictive information. <br><br></p>
<p><strong>3. Type conversion</strong><br />
All predictors were originally stored as ordered factors with string
levels (<code>"1"</code> to <code>"10"</code>). To enable numerical
computation, they were converted to numeric using
<code>as.numeric(as.character(.))</code>. The intermediate
<code>as.character()</code> step prevents R from returning factor level
indices instead of the actual values.</p>
<p><br><br></p>
<pre class="r"><code>dim(BreastCancer)</code></pre>
<pre><code>## [1] 699  11</code></pre>
<pre class="r"><code>dataset &lt;- BreastCancer %&gt;%
  na.omit() %&gt;%
  select(-Id) %&gt;%
  mutate(across(-Class, ~ as.numeric(as.character(.))))

dim(dataset)</code></pre>
<pre><code>## [1] 683  10</code></pre>
<pre class="r"><code>anyNA(dataset)</code></pre>
<pre><code>## [1] FALSE</code></pre>
<pre class="r"><code>glimpse(dataset)</code></pre>
<pre><code>## Rows: 683
## Columns: 10
## $ Cl.thickness    &lt;dbl&gt; 5, 5, 3, 6, 4, 8, 1, 2, 2, 4, 1, 2, 5, 1, 8, 7, 4, 4, …
## $ Cell.size       &lt;dbl&gt; 1, 4, 1, 8, 1, 10, 1, 1, 1, 2, 1, 1, 3, 1, 7, 4, 1, 1,…
## $ Cell.shape      &lt;dbl&gt; 1, 4, 1, 8, 1, 10, 1, 2, 1, 1, 1, 1, 3, 1, 5, 6, 1, 1,…
## $ Marg.adhesion   &lt;dbl&gt; 1, 5, 1, 1, 3, 8, 1, 1, 1, 1, 1, 1, 3, 1, 10, 4, 1, 1,…
## $ Epith.c.size    &lt;dbl&gt; 2, 7, 2, 3, 2, 7, 2, 2, 2, 2, 1, 2, 2, 2, 7, 6, 2, 2, …
## $ Bare.nuclei     &lt;dbl&gt; 1, 10, 2, 4, 1, 10, 10, 1, 1, 1, 1, 1, 3, 3, 9, 1, 1, …
## $ Bl.cromatin     &lt;dbl&gt; 3, 3, 3, 3, 3, 9, 3, 3, 1, 2, 3, 2, 4, 3, 5, 4, 2, 3, …
## $ Normal.nucleoli &lt;dbl&gt; 1, 2, 1, 7, 1, 7, 1, 1, 1, 1, 1, 1, 4, 1, 5, 3, 1, 1, …
## $ Mitoses         &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 5, 1, 1, 1, 1, 1, 4, 1, 1, 1, …
## $ Class           &lt;fct&gt; benign, benign, benign, benign, benign, malignant, ben…</code></pre>
<p><br><br><br><br></p>
</div>
<div id="class-distribution" class="section level4">
<h4>3-2. Class Distribution</h4>
<p><br> The target variable <code>Class</code> is binary, consisting of
<strong>benign</strong> and <strong>malignant</strong> tumor diagnoses.
As shown in the plot below, the dataset contains <strong>444 benign
(65.0%)</strong> and <strong>239 malignant (35.0%)</strong>
observations, indicating a moderate class imbalance.</p>
<p>To account for this imbalance, stratified sampling will be applied
during the train/test split to ensure both subsets preserve the original
class ratio. Given this class imbalance, sensitivity and ROC/AUC were
prioritized over overall accuracy as the primary evaluation metrics.
<br><br><br></p>
<pre class="r"><code>ggplot(dataset, aes(x = Class, fill = Class)) +
  geom_bar() +
  geom_text(stat = &quot;count&quot;, aes(label = after_stat(count)), vjust = -0.5) +
  theme_minimal() +
  labs(title = &quot;Class Distribution&quot;, x = &quot;Diagnosis&quot;, y = &quot;Count&quot;) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.08))) +
  guides(fill = &quot;none&quot;)</code></pre>
<p><img src="breast_cancer_ml_files/figure-html/class_distribution-1.png" width="672" /></p>
<p><br><br><br><br></p>
</div>
<div id="feature-distributions" class="section level4">
<h4>3-3. Feature Distributions</h4>
<p><br> To examine how each predictor differs across tumor classes,
density plots and boxplots were generated for all nine features.</p>
<p>Density plots show the overall shape of each feature distribution and
the degree of overlap between benign and malignant cases. <br> Boxplots
complement this by highlighting differences in medians, interquartile
ranges, and potential outliers.</p>
<p><br><br><br></p>
<pre class="r"><code>dataset %&gt;%
  select(where(is.numeric), Class) %&gt;%
  pivot_longer(-Class, names_to = &quot;variable&quot;, values_to = &quot;value&quot;) %&gt;%
  ggplot(aes(x = value, fill = Class)) +
  geom_density(alpha = 0.5) +
  facet_wrap(~ variable, scales = &quot;free&quot;) +
  theme_minimal() +
  labs(title = &quot;Feature Distributions by Class&quot;)</code></pre>
<p><img src="breast_cancer_ml_files/figure-html/feature_distributions-1.png" width="960" /></p>
<p><br><br></p>
<pre class="r"><code>dataset %&gt;%
  select(where(is.numeric), Class) %&gt;%
  pivot_longer(-Class, names_to = &quot;variable&quot;, values_to = &quot;value&quot;) %&gt;%
  ggplot(aes(x = Class, y = value, fill = Class)) +
  geom_boxplot(outlier.shape = 21, outlier.size = 1.5) +
  facet_wrap(~ variable, scales = &quot;free_y&quot;) +
  theme_classic() +
  labs(title = &quot;Feature Distributions by Class (Boxplot)&quot;) +
  guides(fill = &quot;none&quot;)</code></pre>
<p><img src="breast_cancer_ml_files/figure-html/boxplot-1.png" width="960" /></p>
<p><br></p>
<p>Based on the plots, features such as <code>Bare.nuclei</code>,
<code>Cell.shape</code>, <code>Cell.size</code>, and
<code>Bl.cromatin</code> appear to show relatively clear separation
between benign and malignant cases, suggesting that they may serve as
strong predictors in subsequent models. In contrast,
<code>Mitoses</code> showed substantial overlap between classes,
indicating weaker discriminative power.</p>
<p><br><br><br><br></p>
</div>
<div id="correlation-analysis" class="section level4">
<h4>3-4. Correlation Analysis</h4>
<p><br> A correlation matrix was computed to examine pairwise
relationships among the nine predictors and to assess potential
multicollinearity prior to modeling.</p>
<p><br><br></p>
<pre class="r"><code>cor_matrix &lt;- dataset %&gt;%
  select(where(is.numeric)) %&gt;%
  cor()

corrplot(cor_matrix,
         method      = &quot;color&quot;,
         type        = &quot;upper&quot;,
         addCoef.col = &quot;black&quot;,
         number.cex  = 0.7,
         tl.cex      = 0.8,
         diag        = FALSE,
         title       = &quot;Correlation Matrix of Predictors&quot;,
         mar         = c(0,0,1,0))</code></pre>
<p><img src="breast_cancer_ml_files/figure-html/correlation_matrix-1.png" width="768" /></p>
<p><br></p>
<p>The strongest correlation was observed between <code>Cell.size</code>
and <code>Cell.shape</code> (r = 0.91), suggesting that these variables
capture highly similar information. In addition, <code>Cell.size</code>
showed strong correlations with several other predictors, indicating it
may contribute to multicollinearity.</p>
<p>In contrast, <code>Mitoses</code> exhibited consistently weak
correlations with other features, suggesting limited redundancy.</p>
<p>These findings motivated a formal assessment of multicollinearity
using Variance Inflation Factors (VIF) in the following section.</p>
<p><br><br><br><br></p>
</div>
</div>
<div id="multicollinearity-check-vif" class="section level3">
<h3>4. Multicollinearity Check (VIF)</h3>
<p><br></p>
<p>Although the correlation matrix showed several moderately high
pairwise correlations, a formal multicollinearity assessment was
conducted using the <strong>Variance Inflation Factor (VIF)</strong>.
Unlike pairwise correlations, VIF measures how much the variance of each
coefficient is inflated due to its relationships with all other
predictors.</p>
<p><br></p>
<p>A logistic regression model was fitted on the full dataset solely for
the purpose of VIF computation, prior to any train/test split. VIF
values were interpreted using the following thresholds:</p>
<ul>
<li>VIF &lt; 5 : acceptable</li>
<li>VIF 5–10 : moderate concern</li>
<li>VIF &gt; 10 : severe multicollinearity</li>
</ul>
<p><br></p>
<pre class="r"><code>vif_model &lt;- glm(Class ~ ., data = dataset, family = binomial)

vif_result &lt;- vif(vif_model)  
print(vif_result)</code></pre>
<pre><code>##    Cl.thickness       Cell.size      Cell.shape   Marg.adhesion    Epith.c.size 
##        1.187603        2.819291        2.762855        1.186289        1.347315 
##     Bare.nuclei     Bl.cromatin Normal.nucleoli         Mitoses 
##        1.141698        1.214951        1.219882        1.041650</code></pre>
<p><br></p>
<pre class="r"><code>vif_df &lt;- data.frame(
    Variable = names(vif_result),
    VIF      = as.numeric(vif_result)
)

ggplot(vif_df, aes(x = reorder(Variable, VIF), y = VIF, fill = VIF &gt; 5)) +
    geom_col() +
    geom_hline(yintercept = 5,  linetype = &quot;dashed&quot;, color = &quot;orange&quot;) +
    geom_hline(yintercept = 10, linetype = &quot;dashed&quot;, color = &quot;red&quot;) +
    coord_flip() +
    scale_fill_manual(values = c(&quot;steelblue&quot;, &quot;tomato&quot;),
                      labels = c(&quot;VIF ≤ 5&quot;, &quot;VIF &gt; 5&quot;),
                      name   = &quot;&quot;) +
    theme_minimal() +
    labs(title = &quot;Variance Inflation Factor (VIF)&quot;,
         x = &quot;&quot;, y = &quot;VIF&quot;)</code></pre>
<p><img src="breast_cancer_ml_files/figure-html/vif_plot-1.png" width="672" /></p>
<p><br></p>
<p>All nine predictors had VIF values below 5, indicating no evidence of
severe multicollinearity. Notably, although a strong pairwise
correlation was observed between <code>Cell.size</code> and
<code>Cell.shape</code> (r = 0.91) in the previous section, their VIF
values remained within an acceptable range. This suggests that variance
inflation is limited when all predictors are considered jointly.</p>
<p>Therefore, all nine predictors were retained for subsequent modeling.
However, given the observed pairwise correlations, LASSO regularization
was applied to perform data-driven variable selection and to improve the
stability of coefficient estimates.</p>
<p><br><br><br><br></p>
</div>
<div id="model-development" class="section level3">
<h3>5. Model Development</h3>
<p><br></p>
<p>All models were trained on 70% of the data and evaluated on the
remaining 30%, using stratified sampling to preserve the original class
ratio across both subsets.</p>
<p><br></p>
<pre class="r"><code>set.seed(42)
train_idx &lt;- createDataPartition(dataset$Class, p = 0.7, list = FALSE)
train &lt;- dataset[train_idx, ]
test  &lt;- dataset[-train_idx, ]</code></pre>
<p><br><br><br></p>
<div id="logistic-regression" class="section level4">
<h4>5-1. Logistic Regression</h4>
<p><br></p>
<p>Logistic regression was used as the baseline model, fitted using all
nine predictors. As a parametric model, it provides interpretable
coefficients, allowing direct assessment of the direction and magnitude
of each predictor’s association with malignancy.</p>
<p><br></p>
<pre class="r"><code>logit_model &lt;- glm(Class ~ ., data = train, family = binomial)
summary(logit_model)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Class ~ ., family = binomial, data = train)
## 
## Coefficients:
##                 Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)     -9.94504    1.34220  -7.409 1.27e-13 ***
## Cl.thickness     0.57128    0.16690   3.423  0.00062 ***
## Cell.size       -0.09245    0.23124  -0.400  0.68929    
## Cell.shape       0.38900    0.26543   1.466  0.14278    
## Marg.adhesion    0.37560    0.13169   2.852  0.00434 ** 
## Epith.c.size     0.06196    0.16214   0.382  0.70236    
## Bare.nuclei      0.29833    0.10105   2.952  0.00316 ** 
## Bl.cromatin      0.42573    0.19595   2.173  0.02981 *  
## Normal.nucleoli  0.23588    0.11890   1.984  0.04728 *  
## Mitoses          0.49195    0.36248   1.357  0.17473    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 620.686  on 478  degrees of freedom
## Residual deviance:  83.481  on 469  degrees of freedom
## AIC: 103.48
## 
## Number of Fisher Scoring iterations: 8</code></pre>
<p><br></p>
<pre class="r"><code>logit_prob &lt;- predict(logit_model, newdata = test, type = &quot;response&quot;)
logit_pred &lt;- ifelse(logit_prob &gt; 0.5, &quot;malignant&quot;, &quot;benign&quot;)
logit_pred &lt;- factor(logit_pred, levels = levels(test$Class))
confusionMatrix(logit_pred, test$Class, positive = &quot;malignant&quot;)</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##            Reference
## Prediction  benign malignant
##   benign       131         3
##   malignant      2        68
##                                          
##                Accuracy : 0.9755         
##                  95% CI : (0.9437, 0.992)
##     No Information Rate : 0.652          
##     P-Value [Acc &gt; NIR] : &lt;2e-16         
##                                          
##                   Kappa : 0.9458         
##                                          
##  Mcnemar&#39;s Test P-Value : 1              
##                                          
##             Sensitivity : 0.9577         
##             Specificity : 0.9850         
##          Pos Pred Value : 0.9714         
##          Neg Pred Value : 0.9776         
##              Prevalence : 0.3480         
##          Detection Rate : 0.3333         
##    Detection Prevalence : 0.3431         
##       Balanced Accuracy : 0.9714         
##                                          
##        &#39;Positive&#39; Class : malignant      
## </code></pre>
<p><br></p>
<p>Among the predictors, <code>Cl.thickness</code>,
<code>Marg.adhesion</code>, <code>Bare.nuclei</code>,
<code>Bl.cromatin</code>, and <code>Normal.nucleoli</code> were
statistically significant (p &lt; 0.05). <br><br> Notably,
<code>Cell.size</code> returned a negative coefficient despite its
strong association with malignancy observed in EDA, likely due to its
high correlation with <code>Cell.shape</code> (r = 0.91), which absorbed
much of its predictive contribution. <br><br> This instability in
coefficient estimation motivated the use of LASSO in the following
section.</p>
<p>The model achieved an <strong>accuracy of 97.6%</strong> and a
<strong>sensitivity of 95.8%</strong>, misclassifying three malignant
cases as benign.</p>
<p><br><br><br></p>
</div>
<div id="lasso" class="section level4">
<h4>5-2. LASSO</h4>
<p><br></p>
<p>LASSO (Least Absolute Shrinkage and Selection Operator) was applied
to address the coefficient instability observed in logistic regression.
By imposing an L1 penalty, LASSO shrinks less informative coefficients
toward zero, effectively performing automatic variable selection.</p>
<p>The optimal penalty parameter lambda was selected via 10-fold
cross-validation, using <code>lambda.1se</code>, the largest lambda
within one standard error of the minimum, which favors a simpler model
without substantial loss in predictive performance.</p>
<p><br></p>
<pre class="r"><code>x_train &lt;- model.matrix(Class ~ ., data = train)[, -1]
x_test  &lt;- model.matrix(Class ~ ., data = test)[, -1]
y_train &lt;- ifelse(train$Class == &quot;malignant&quot;, 1, 0)
y_test  &lt;- ifelse(test$Class  == &quot;malignant&quot;, 1, 0)

set.seed(42)
lasso_cv &lt;- cv.glmnet(x_train, y_train,
                      family  = &quot;binomial&quot;,
                      alpha   = 1,
                      nfolds  = 10)
plot(lasso_cv)</code></pre>
<p><img src="breast_cancer_ml_files/figure-html/lasso-1.png" width="672" /></p>
<p><br></p>
<pre class="r"><code>coef(lasso_cv, s = &quot;lambda.1se&quot;)</code></pre>
<pre><code>## 10 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                   lambda.1se
## (Intercept)     -5.654783814
## Cl.thickness     0.293999932
## Cell.size        0.022291895
## Cell.shape       0.290901083
## Marg.adhesion    0.126180239
## Epith.c.size     0.006351731
## Bare.nuclei      0.250414015
## Bl.cromatin      0.178865322
## Normal.nucleoli  0.146072979
## Mitoses          .</code></pre>
<p><br></p>
<pre class="r"><code>lasso_prob &lt;- predict(lasso_cv, newx = x_test, 
                      s    = &quot;lambda.1se&quot;, 
                      type = &quot;response&quot;)
lasso_pred &lt;- ifelse(lasso_prob &gt; 0.5, &quot;malignant&quot;, &quot;benign&quot;)
lasso_pred &lt;- factor(lasso_pred, levels = levels(test$Class))

confusionMatrix(lasso_pred, test$Class, positive = &quot;malignant&quot;)</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##            Reference
## Prediction  benign malignant
##   benign       131         4
##   malignant      2        67
##                                           
##                Accuracy : 0.9706          
##                  95% CI : (0.9371, 0.9891)
##     No Information Rate : 0.652           
##     P-Value [Acc &gt; NIR] : &lt;2e-16          
##                                           
##                   Kappa : 0.9348          
##                                           
##  Mcnemar&#39;s Test P-Value : 0.6831          
##                                           
##             Sensitivity : 0.9437          
##             Specificity : 0.9850          
##          Pos Pred Value : 0.9710          
##          Neg Pred Value : 0.9704          
##              Prevalence : 0.3480          
##          Detection Rate : 0.3284          
##    Detection Prevalence : 0.3382          
##       Balanced Accuracy : 0.9643          
##                                           
##        &#39;Positive&#39; Class : malignant       
## </code></pre>
<p><br></p>
<p>LASSO eliminated <code>Mitoses</code> from the model by shrinking its
coefficient to zero, consistent with its weak discriminative power
observed in EDA.</p>
<p>In addition, <code>Cell.size</code>, which showed a negative
coefficient in logistic regression, was assigned a positive coefficient
under LASSO, reflecting its true positive association with
malignancy.</p>
<p>The model achieved an <strong>accuracy of 97.1%</strong> and a
<strong>sensitivity of 94.4%</strong>, representing a slight decrease
compared to logistic regression. However, the resulting model is more
parsimonious and provides more stable coefficient estimates, making it
preferable when interpretability is a priority.</p>
<p><br><br><br></p>
</div>
<div id="decision-tree" class="section level4">
<h4>5-3. Decision Tree</h4>
<p><br></p>
<p>A decision tree was used to provide an interpretable, rule-based
classification model. <br> Unlike logistic regression, decision trees
require no assumptions about linearity or variable distributions, and
the resulting structure can be directly translated into clinical
decision rules.</p>
<p>To prevent overfitting, pruning was applied by selecting the optimal
complexity parameter (cp) based on cross-validated error.</p>
<p><br></p>
<pre class="r"><code>tree_model &lt;- rpart(Class ~ .,
                    data    = train,
                    method  = &quot;class&quot;,
                    control = rpart.control(cp = 0.01))

printcp(tree_model)</code></pre>
<pre><code>## 
## Classification tree:
## rpart(formula = Class ~ ., data = train, method = &quot;class&quot;, control = rpart.control(cp = 0.01))
## 
## Variables actually used in tree construction:
## [1] Cell.shape Cell.size 
## 
## Root node error: 168/479 = 0.35073
## 
## n= 479 
## 
##         CP nsplit rel error  xerror     xstd
## 1 0.785714      0   1.00000 1.00000 0.062167
## 2 0.065476      1   0.21429 0.23214 0.035627
## 3 0.010000      2   0.14881 0.15476 0.029516</code></pre>
<pre class="r"><code>plotcp(tree_model)</code></pre>
<p><img src="breast_cancer_ml_files/figure-html/decision_tree-1.png" width="672" /></p>
<p><br></p>
<pre class="r"><code>best_cp     &lt;- tree_model$cptable[which.min(tree_model$cptable[, &quot;xerror&quot;]), &quot;CP&quot;]
tree_pruned &lt;- prune(tree_model, cp = best_cp)

rpart.plot(tree_pruned,
           type  = 4,
           extra = 104,
           main  = &quot;Pruned Decision Tree&quot;)</code></pre>
<p><img src="breast_cancer_ml_files/figure-html/tree_pruned-1.png" width="672" /></p>
<p><br></p>
<pre class="r"><code>tree_pred &lt;- predict(tree_pruned, newdata = test, type = &quot;class&quot;)
confusionMatrix(tree_pred, test$Class, positive = &quot;malignant&quot;)</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##            Reference
## Prediction  benign malignant
##   benign       127         6
##   malignant      6        65
##                                           
##                Accuracy : 0.9412          
##                  95% CI : (0.8995, 0.9692)
##     No Information Rate : 0.652           
##     P-Value [Acc &gt; NIR] : &lt;2e-16          
##                                           
##                   Kappa : 0.8704          
##                                           
##  Mcnemar&#39;s Test P-Value : 1               
##                                           
##             Sensitivity : 0.9155          
##             Specificity : 0.9549          
##          Pos Pred Value : 0.9155          
##          Neg Pred Value : 0.9549          
##              Prevalence : 0.3480          
##          Detection Rate : 0.3186          
##    Detection Prevalence : 0.3480          
##       Balanced Accuracy : 0.9352          
##                                           
##        &#39;Positive&#39; Class : malignant       
## </code></pre>
<p><br></p>
<p>The pruned tree utilized only two predictors, <code>Cell.size</code>
and <code>Cell.shape</code>, to construct three terminal nodes. <br> A
simple decision rule emerged: observations with <code>Cell.size</code>
below 3 were classified as benign with a probability of 97%, while those
with both <code>Cell.size</code> and <code>Cell.shape</code> at or above
3 were classified as malignant with a probability of 92%.</p>
<p>The model achieved an <strong>accuracy of 94.1%</strong> and a
<strong>sensitivity of 91.6%</strong>, lower than logistic regression
and LASSO. <br> This reduction in performance reflects the trade-off
between interpretability and predictive power. The tree relies on only
two predictors, discarding information from the remaining seven
features.</p>
<p><br><br><br></p>
</div>
<div id="random-forest" class="section level4">
<h4>5-4. Random Forest</h4>
<p><br></p>
<p>Random Forest was used as an ensemble method to improve predictive
performance beyond a single decision tree.<br> It aggregates predictions
from 500 decision trees, each trained on a random subset of features,
thereby reducing variance and improving generalization. <br></p>
<pre class="r"><code>set.seed(42)
rf_model &lt;- randomForest(Class ~ .,
                         data       = train,
                         ntree      = 500,
                         mtry       = floor(sqrt(ncol(train) - 1)),
                         importance = TRUE)

varImpPlot(rf_model,
           main = &quot;Random Forest: Variable Importance&quot;,
           pch  = 16, col = &quot;darkblue&quot;)</code></pre>
<p><img src="breast_cancer_ml_files/figure-html/random_forest-1.png" width="672" /></p>
<p><br></p>
<pre class="r"><code>rf_prob &lt;- predict(rf_model, newdata = test, type = &quot;prob&quot;)[, &quot;malignant&quot;]
rf_pred &lt;- predict(rf_model, newdata = test, type = &quot;response&quot;)

confusionMatrix(rf_pred, test$Class, positive = &quot;malignant&quot;)</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##            Reference
## Prediction  benign malignant
##   benign       131         2
##   malignant      2        69
##                                           
##                Accuracy : 0.9804          
##                  95% CI : (0.9506, 0.9946)
##     No Information Rate : 0.652           
##     P-Value [Acc &gt; NIR] : &lt;2e-16          
##                                           
##                   Kappa : 0.9568          
##                                           
##  Mcnemar&#39;s Test P-Value : 1               
##                                           
##             Sensitivity : 0.9718          
##             Specificity : 0.9850          
##          Pos Pred Value : 0.9718          
##          Neg Pred Value : 0.9850          
##              Prevalence : 0.3480          
##          Detection Rate : 0.3382          
##    Detection Prevalence : 0.3480          
##       Balanced Accuracy : 0.9784          
##                                           
##        &#39;Positive&#39; Class : malignant       
## </code></pre>
<p><br></p>
<p>The variable importance plot indicates that <code>Cell.size</code>,
<code>Bare.nuclei</code>, and <code>Cell.shape</code> are the most
influential predictors, consistent with findings from EDA and the
decision tree model. <br> Unlike the decision tree, Random Forest
leverages all nine predictors, allowing it to capture more complex
relationships in the data.</p>
<p>The model achieved an <strong>accuracy of 97.1%</strong> and a
<strong>sensitivity of 95.8%</strong>, comparable to logistic
regression, while providing greater robustness to overfitting.</p>
<p><br><br><br></p>
</div>
<div id="xgboost" class="section level4">
<h4>5-5. XGBoost</h4>
<p><br></p>
<p>XGBoost (Extreme Gradient Boosting) was used as a gradient boosting
method that builds trees sequentially, with each tree correcting the
errors of the previous one. In contrast to Random Forest, which builds
trees independently, XGBoost optimizes a regularized objective function
and often achieves higher predictive performance.</p>
<p>Key hyperparameters included a learning rate (eta) of 0.1, a maximum
tree depth of 4, and a subsampling rate of 0.8.<br> Early stopping was
applied based on validation AUC, halting training if no improvement was
observed for 10 consecutive rounds.</p>
<p><br></p>
<pre class="r"><code>dtrain &lt;- xgb.DMatrix(data = x_train, label = y_train)
dtest  &lt;- xgb.DMatrix(data = x_test,  label = y_test)

params &lt;- list(
  objective        = &quot;binary:logistic&quot;,
  eval_metric      = &quot;auc&quot;,
  eta              = 0.1,
  max_depth        = 4,
  subsample        = 0.8,
  colsample_bytree = 0.8
)

set.seed(42)
xgb_model &lt;- xgb.train(params                = params,
                        data                  = dtrain,
                        nrounds               = 100,
                        evals                 = list(train = dtrain, test = dtest),
                        verbose               = 1,
                        early_stopping_rounds = 10)</code></pre>
<pre><code>## Multiple eval metrics are present. Will use test_auc for early stopping.
## Will train until test_auc hasn&#39;t improved in 10 rounds.
## 
## [1]  train-auc:0.977109  test-auc:0.967489 
## [2]  train-auc:0.977320  test-auc:0.970454 
## [3]  train-auc:0.988344  test-auc:0.992958 
## [4]  train-auc:0.987684  test-auc:0.993381 
## [5]  train-auc:0.991253  test-auc:0.993328 
## [6]  train-auc:0.991971  test-auc:0.994387 
## [7]  train-auc:0.992172  test-auc:0.994705 
## [8]  train-auc:0.993138  test-auc:0.995446 
## [9]  train-auc:0.993426  test-auc:0.995499 
## [10] train-auc:0.993426  test-auc:0.996135 
## [11] train-auc:0.995052  test-auc:0.996558 
## [12] train-auc:0.995091  test-auc:0.996611 
## [13] train-auc:0.995263  test-auc:0.996505 
## [14] train-auc:0.995694  test-auc:0.996929 
## [15] train-auc:0.995598  test-auc:0.996611 
## [16] train-auc:0.995560  test-auc:0.996611 
## [17] train-auc:0.995885  test-auc:0.996823 
## [18] train-auc:0.996306  test-auc:0.996823 
## [19] train-auc:0.996574  test-auc:0.997141 
## [20] train-auc:0.996612  test-auc:0.997141 
## [21] train-auc:0.996919  test-auc:0.997458 
## [22] train-auc:0.997282  test-auc:0.997776 
## [23] train-auc:0.997378  test-auc:0.997458 
## [24] train-auc:0.997550  test-auc:0.997353 
## [25] train-auc:0.997722  test-auc:0.997247 
## [26] train-auc:0.997895  test-auc:0.997247 
## [27] train-auc:0.998009  test-auc:0.997035 
## [28] train-auc:0.998124  test-auc:0.997247 
## [29] train-auc:0.998316  test-auc:0.997035 
## [30] train-auc:0.998373  test-auc:0.997035 
## [31] train-auc:0.998545  test-auc:0.997035 
## Stopping. Best iteration:
## [32] train-auc:0.998679  test-auc:0.996823
## 
## [32] train-auc:0.998679  test-auc:0.996823</code></pre>
<p><br></p>
<pre class="r"><code>xgb_imp &lt;- xgb.importance(feature_names = colnames(x_train), model = xgb_model)
xgb.plot.importance(xgb_imp, main = &quot;XGBoost: Variable Importance&quot;)</code></pre>
<p><img src="breast_cancer_ml_files/figure-html/xgb_imp-1.png" width="672" /></p>
<p><br></p>
<pre class="r"><code>xgb_prob &lt;- predict(xgb_model, dtest)
xgb_pred &lt;- ifelse(xgb_prob &gt; 0.5, &quot;malignant&quot;, &quot;benign&quot;)
xgb_pred &lt;- factor(xgb_pred, levels = levels(test$Class))
confusionMatrix(xgb_pred, test$Class, positive = &quot;malignant&quot;)</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##            Reference
## Prediction  benign malignant
##   benign       131         4
##   malignant      2        67
##                                           
##                Accuracy : 0.9706          
##                  95% CI : (0.9371, 0.9891)
##     No Information Rate : 0.652           
##     P-Value [Acc &gt; NIR] : &lt;2e-16          
##                                           
##                   Kappa : 0.9348          
##                                           
##  Mcnemar&#39;s Test P-Value : 0.6831          
##                                           
##             Sensitivity : 0.9437          
##             Specificity : 0.9850          
##          Pos Pred Value : 0.9710          
##          Neg Pred Value : 0.9704          
##              Prevalence : 0.3480          
##          Detection Rate : 0.3284          
##    Detection Prevalence : 0.3382          
##       Balanced Accuracy : 0.9643          
##                                           
##        &#39;Positive&#39; Class : malignant       
## </code></pre>
<p><br></p>
<p>Consistent with previous models, <code>Cell.size</code>,
<code>Bare.nuclei</code>, and <code>Cell.shape</code> ranked among the
most important features. The consistency of variable importance across
models suggests that these predictors carry the most discriminative
information for breast cancer classification.</p>
<p>The model achieved an <strong>accuracy of 97.1%</strong> and a
<strong>sensitivity of 95.8%</strong>, comparable to logistic regression
and Random Forest.</p>
<p><br><br><br><br></p>
</div>
</div>
<div id="model-evaluation" class="section level3">
<h3>6. Model Evaluation</h3>
<p><br><br></p>
<p>Model performance was evaluated across all five classifiers using
confusion matrices and ROC/AUC analysis. Given the clinical context,
<strong>sensitivity</strong> was treated as the primary evaluation
metric, as failing to detect a malignant tumor carries significantly
greater clinical risk than a false positive.</p>
<p><br><br></p>
<div id="confusion-matrix" class="section level4">
<h4>6-1. Confusion Matrix</h4>
<p><br></p>
<p>The table below summarizes key performance metrics for all five
models on the test set.</p>
<p><br></p>
<table>
<caption>Model Performance Comparison on Test Set</caption>
<thead>
<tr class="header">
<th align="left">Model</th>
<th align="center">Accuracy</th>
<th align="center">Sensitivity</th>
<th align="center">Specificity</th>
<th align="center">FN</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Logistic Regression</td>
<td align="center">0.9755</td>
<td align="center">0.9577</td>
<td align="center">0.9850</td>
<td align="center">3</td>
</tr>
<tr class="even">
<td align="left">LASSO</td>
<td align="center">0.9706</td>
<td align="center">0.9437</td>
<td align="center">0.9850</td>
<td align="center">4</td>
</tr>
<tr class="odd">
<td align="left">Decision Tree</td>
<td align="center">0.9412</td>
<td align="center">0.9155</td>
<td align="center">0.9549</td>
<td align="center">6</td>
</tr>
<tr class="even">
<td align="left">Random Forest</td>
<td align="center">0.9706</td>
<td align="center">0.9577</td>
<td align="center">0.9850</td>
<td align="center">3</td>
</tr>
<tr class="odd">
<td align="left">XGBoost</td>
<td align="center">0.9706</td>
<td align="center">0.9577</td>
<td align="center">0.9850</td>
<td align="center">3</td>
</tr>
</tbody>
</table>
<p><br></p>
<p>Logistic Regression, Random Forest, and XGBoost achieved the highest
sensitivity (95.8%), each misclassifying three malignant cases as
benign.</p>
<p>LASSO showed a slightly lower sensitivity (94.4%), likely due to the
exclusion of <code>Mitoses</code>. The Decision Tree exhibited the
lowest sensitivity (91.6%), reflecting the limitation of relying on only
two predictors.</p>
<p>All models substantially outperformed the No Information Rate
(65.2%), indicating that each model provides meaningful discriminative
power beyond naive classification.</p>
<p><br><br><br></p>
<h4>
6-2. ROC / AUC Comparison
</h4>
<p><br></p>
<p><br><br><br><br></p>
</div>
</div>
<div id="conclusion" class="section level3">
<h3>7. Conclusion</h3>
<p><br><br> Case 1: Banking Services</p>
<p>The analysis of customer subscription patterns revealed that CKING
(Checking Account) is a central service with high demand, and its strong
association with SVG (Savings Account) presents a valuable cross-selling
opportunity. By targeting SVG customers with personalized CKING
recommendations, banks can drive service adoption while enhancing
customer loyalty. This approach can be further scaled using predictive
analytics to identify other key service pairs, tailoring campaigns to
maximize customer satisfaction and retention.</p>
<p><br></p>
</div>
</div>


<br><br>
<footer>
  <p class="copyright text-muted" align="center">Copyright &copy; 2024 Jiye Choi</p>
</footer>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4,h5",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = false;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
